### PR TITLE
Wire-framed TP list with example data set & TempApp component (feel free to update/delete)

### PR DESCRIPTION
**Pull request by kamasood**

### CODE REVIEW

**Review by Zynh0722 — APPROVED** [review]
lgtm

**Comment by Zynh0722** [comment]
@kamasood Also, make sure you mark what issues this PR solves in a comment or in the description.

Ideally your commits should have like, "Fixed #2" in the titles when applicable

**Comment by Zynh0722** [comment]
also @kamasood did you first make sure to merge from main and check for conflicts before making the PR?

**Review by Zynh0722 — CHANGES_REQUESTED** [review]
Check for merge, also mark fixed issues

**Comment by kamasood** [comment]
double-checked, main is up to date and merged, will do on the commit messages going forward, thx!

**Review by Zynh0722 — APPROVED** [review]

**Pull request merged**
